### ISSUE TITLE
JsonDecodingException

### ISSUE THREAD

**Issue by asad-awadia** [nemoengineering/meilisearch-kotlin#59]
Basic repro for the issue. Throws a json decoding exception even though the response looks right

ktor version 2.2.1

```
suspend fun main() {
  val client = Meilisearch {
    port = 7700
    host = "localhost"
    apiKey = "xyz" // optional
  }
  println(client.listIndexes())
}
```

```
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: {"results":[{"uid":"index","createdAt":"2022-12-11T22:25:25.139523673Z","updatedAt":"2022-12-13T02:47:07.434350022Z","primaryKey":"id"}],"offset":0,"limit":20,"total":1}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:530)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:528)
```

**Comment by asad-awadia** [comment]
i suggest using the vertx webclient instead of ktor
